server.port: 8181
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://localhost:3306/bankservice
spring.datasource.username: root
spring.datasource.password: root
bankapp.jwtSecret: bankAppSecretKey
bankapp.jwtExpirationMs: 86400000
spring.mvc.pathmatch.matching-strategy: ant-path-matcher


